version: '2.3'

services:
  db:
    image: postgres:latest
    container_name: postgres-dating-db
    environment:
      POSTGRES_DB: dating_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-dating-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
